### ISSUE TITLE
Error: TextEncoder is not defined

### ISSUE THREAD

**Issue by ImYuya** [solana-labs/example-messagefeed#149]
What can be done about below?
When I executed `npm run dev-server`  I got the following error:

```
Error importing `index.js`: ReferenceError: TextEncoder is not defined
    at eval (webpack:///./wasm/index.js?:35:25)
    at Module../wasm/index.js (/home/tontest/example-messagefeed/dist/1.server.js:118:1)
    at __webpack_require__ (/home/tontest/example-messagefeed/dist/server.js:67:30)
    at Object.eval (webpack:///./src/server/prediction-poll.js?:37:13)
    at eval (webpack:///./src/server/prediction-poll.js?:305:30)
    at Object../src/server/prediction-poll.js (/home/tontest/example-messagefeed/dist/1.server.js:70:1)
    at __webpack_require__ (/home/tontest/example-messagefeed/dist/server.js:67:30)
    at Object.eval (webpack:///./src/server/index.js?:41:23)
    at eval (webpack:///./src/server/index.js?:249:30)
    at Object../src/server/index.js (/home/tontest/example-messagefeed/dist/1.server.js:46:1)
```

**Comment by jstarry** [comment]
@ImYuya try updating your version of node. I think v12.6.0 should do the trick
